// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjwwwtivxghqdtkfzmya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qd3d3dGl2eGdocWR0a2Z6bXlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTY2NDIsImV4cCI6MjA2OTAzMjY0Mn0.6JmroD6GjCOurVUtL83h_3m38VAHCCNamMHn2BTsorw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});